app = "corvis-ai"              # <── the app you really want
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  METRICS_PORT = 9200          # strings are fine inside [env]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [[http_service.listeners]]
    portals = ["https"]
    tls_options = { alpn = ["http/1.1"] }

[metrics]
  port = 9200                  # ← NO quotes, must be an int
  path = "/metrics"
