[project]
name = "volunteer-bot"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [

  "aiosqlite>=0.20",
  "PyNaCl>=1.5",
  "SQLAlchemy>=2.0",
  "alembic>=1.13",
  "google-genai>=0.4",
  "python-dotenv>=0.20",
  "pydantic>=2",
  "pydantic-settings",

  "undetected_chromedriver>=3",
  "discord.py>=2.3",
  "selenium>=4",
  "requests>=2"
]

[project.optional-dependencies]
discord = ["discord.py[voice]>=2.3"]
dev = ["pytest>=8", "pytest-asyncio>=0.23", "ruff>=0.4", "black>=24.1", "mypy>=1.9"]

[tool.setuptools]
packages = { find = { where = [ "." ], include = ["bot_core*", "bot_plugins*", "db*", "migrations*"] } }

[project.entry-points."bot_plugins"]
builtin = "bot_plugins.commands"

[project.scripts]
volunteer-bot = "bot_core.main:main"

[tool.mypy]
exclude = [
    "tests/helpers/mocks.py",
    "tests/helpers/__init__.py"
]
