from __future__ import annotations

class YouTubeTranscriptApi:
    @staticmethod
    def get_transcript(
        video_id: str, *, languages: list[str] | None = ..., cookies: str | None = ...
    ) -> list[dict[str, object]]: ...
    @staticmethod
    def list_transcripts(video_id: str, *, cookies: str | None = ...) -> object: ...

class NoTranscriptFound(Exception): ...
class TranscriptsDisabled(Exception): ...
class VideoUnavailable(Exception): ...
